### ISSUE TITLE
创建后显示得还是 README 文档

### ISSUE THREAD

**Issue by phh95** [x1ah/gena-template#4]
请问创建完打开网址之后，为什么显示的还是原来的 readme 文档呢？   https://phh95.github.io/tools_box/

**Comment by x1ah** [comment]
我看已经更新了，刚创建项目生成网页需要一点点时间，另外可能命中缓存，所以可能等几分钟访问才是正常的。

phh95 ***@***.***>于2021年9月30日 周四12:17写道：

**Comment by phh95** [comment]
谢谢，看了下可以正常使用了，谢谢你
