### ISSUE TITLE
无法更改内容

### ISSUE THREAD

**Issue by haorenzhou** [x1ah/gena-template#7]
版主，我修改了网址后发现一致无法成功更新，系统报错如下，想问一下具体是什么问题？
<img width="910" alt="image" src="https://user-images.githubusercontent.com/75919246/232800149-0dba8fef-9887-4761-b66a-1f053a1f83c6.png">
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/75919246/232800393-026eb512-77c4-4b18-a3c5-af0c00255cc6.png">

**Comment by x1ah** [comment]
现在还有问题吗？

**Comment by haorenzhou** [comment]
好了，我发现原因是有一行的name前的横杠少了个空格。
